#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#========================================
# Integration settings
#========================================
spring:
  application:
    name: api-sm-loader
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: dbconnection-pool
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
    show-sql: false
  security:
    oauth2:
      client:
        provider:
          support-management:
            token-uri:  ${integration.support-management.token-uri}
        registration:
          support-management:
            authorization-grant-type: client_credentials
            provider: support-management
            client-id: ${integration.support-management.client-id}
            client-secret: ${integration.support-management.client-secret}
integration:
  open-e:
    external:
      connectTimeout: 5
      readTimeout: 30
    internal:
      connectTimeout: 5
      readTimeout: 30
    external-soap:
      connectTimeout: 5
      readTimeout: 30
    internal-soap:
      connectTimeout: 5
      readTimeout: 30
  support-management:
    connectTimeout: 5
    readTimeout: 30

scheduler:
  caseprocessing:
    cron:
      expression: '${config.scheduler.cron.caseprocessing}'
  shedlock-lock-at-most-for: PT2M

config:
  scheduler:
    cron:
      caseprocessing: '-'