integration:
  open-e-external:
    username: username
    password: password
    url: http://oep-external.url
    family-ids: [ "123" ]
  open-e-internal:
    username: username
    password: password
    url: http://oep-internal.url
    family-ids: [ "456" ]
  open-e-external-soap:
    username: username
    password: password
    url: http://oep-external-soap.url
    family-ids: [ "123" ]
  open-e-internal-soap:
    username: username
    password: password
    url: http://oep-internal-soap.url
    family-ids: [ "456" ]
  support-management:
    url: http://support-management.url

spring:
  security:
    oauth2:
      client:
        provider:
          support-management:
            token-uri: http://token.url
        registration:
          support-management:
            client-id: the-client-id
            client-secret: the-client-secret