integration:
  open-e:
    external:
      username: username
      password: password
      url: http://oep-external.url
    internal:
      username: username
      password: password
      url: http://oep-internal.url
    external-soap:
      username: username
      password: password
      url: http://oep-external-soap.url
    internal-soap:
      username: username
      password: password
      url: http://oep-internal-soap.url
  support-management:
    url: http://support-management.url
  messaging:
    url: http://messaging.url
    channel: channel
    token: token
    mailRecipient: mailRecipient
  party:
    url: http://party.url
# OpenE Services
lamna-synpunkt:
  family-id: 123
  priority: MEDIUM
  category: FEEDBACK_CATEGORY
  type: FEEDBACK_TYPE
sundsvallsforslaget:
  family-id: 456
  priority: MEDIUM
  category: PROPOSAL_CATEGORY
  type: PROPOSAL_TYPE
ersattare-chef:
  family-id: 789
  priority: MEDIUM
  category: ORGANIZATION
  type: EMPLOYMENT
ny-behorighet:
  family-id: 101
  priority: MEDIUM
  category: ADMINISTRATION
  type: PERMISSION
lonevaxling-pension:
  family-id: 111
  priority: MEDIUM
  category: SALARY
  type: PENSION
kontakt-lon-pension:
  family-id: 121
  priority: MEDIUM
  category: SALARY
  type: CONTACT_WANTED
tjugofem-ar-pa-jobbet:
  family-id: 131
  priority: MEDIUM
  category: STATISTICS
  type: OTHER
anmal-sjukfranvaro:
  family-id: 141
  priority: MEDIUM
  category: SALARY
  type: ABSENCE
arbetsgivarintyg:
  family-id: 151
  priority: MEDIUM
  category: ADMINISTRATION
  type: EMPLOYMENT
foretradesratt-ateranstallning:
  family-id: 161
  priority: MEDIUM
  category: ADMINISTRATION
  type: EMPLOYMENT
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false
        column_ordering_strategy: legacy
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          support-management:
            token-uri: http://token.url
          party:
            token-uri: http://token.url
        registration:
          support-management:
            client-id: the-client-id
            client-secret: the-client-secret
          party:
            client-id: client-id
            client-secret: client-secret
  flyway:
    enabled: true
config:
  scheduler:
    fetch-days: 1
    keep-days: 14
    cron:
      caseprocessing: '0 0 */1 * * *'
      dbcleaner: '0 0 0 * * 7'
