integration:
  open-e:
    external:
      username: username
      password: password
      url: http://localhost:${wiremock.server.port:}/open-e-external
    internal:
      username: username
      password: password
      url: http://localhost:${wiremock.server.port:}/open-e-internal
    external-soap:
      username: username
      password: password
      url: http://localhost:${wiremock.server.port:}/open-e-external-soap
    internal-soap:
      username: username
      password: password
      url: http://localhost:${wiremock.server.port:}/open-e-internal-soap
  support-management:
    url: http://localhost:${wiremock.server.port:}/support-management
    token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
    client-id: the-client-id
    client-secret: the-client-secret
    connectTimeout: 10
    readTimeout: 20
  party:
    url: http://localhost:${wiremock.server.port:}/party
    client-id: the-client-id
    client-secret: the-client-secret
    connectTimeout: 10
    readTimeout: 20
# OpenE Services
lamna-synpunkt:
  family-id: 161
  priority: LOW
  category: FEEDBACK_CATEGORY
  type: FEEDBACK_TYPE
sundsvallsforslaget:
  family-id: 370
  priority: MEDIUM
  category: PROPOSAL_CATEGORY
  type: PROPOSAL_TYPE
ersattare-chef:
  family-id: 789
  priority: MEDIUM
  category: ORGANIZATION
  type: EMPLOYMENT
ny-behorighet:
  family-id: 101
  priority: MEDIUM
  category: ADMINISTRATION
  type: PERMISSION
lonevaxling-pension:
  family-id: 111
  priority: MEDIUM
  category: SALARY
  type: PENSION
kontakt-lon-pension:
  family-id: 121
  priority: MEDIUM
  category: SALARY
  type: CONTACT_WANTED
tjugofem-ar-pa-jobbet:
  family-id: 131
  priority: MEDIUM
  category: STATISTICS
  type: OTHER
anmal-sjukfranvaro:
  family-id: 141
  priority: MEDIUM
  category: SALARY
  type: ABSENCE
arbetsgivarintyg:
  family-id: 151
  priority: MEDIUM
  category: ADMINISTRATION
  type: EMPLOYMENT

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
config:
  scheduler:
    fetch-days: 1
    keep-days: 14
    cron:
      caseprocessing: '0 0 */1 * * *'
      dbcleaner: '0 0 0 * * 7'
