#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#========================================
# Integration settings
#========================================
spring:
  application:
    name: api-sm-loader
  security:
    oauth2:
      client:
        registration:
          support-management:
            authorization-grant-type: client_credentials
            provider: support-management
integration:
  open-e-external:
    connectTimeout: 5
    readTimeout: 30
  open-e-internal:
    connectTimeout: 5
    readTimeout: 30
  open-e-external-soap:
    connectTimeout: 5
    readTimeout: 30
  open-e-internal-soap:
    connectTimeout: 5
    readTimeout: 30
  support-management:
    connectTimeout: 5
    readTimeout: 30
