integration:
  open-e:
    external:
      username: username
      password: password
      url: http://oep-external.url
    internal:
      username: username
      password: password
      url: http://oep-internal.url
    external-soap:
      username: username
      password: password
      url: http://oep-external-soap.url
    internal-soap:
      username: username
      password: password
      url: http://oep-internal-soap.url
  support-management:
    url: http://support-management.url
# OpenE Services
lamna-synpunkt:
  family-id: 123
sundsvallsforslaget:
  family-id: 456

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false
        column_ordering_strategy: legacy
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          support-management:
            token-uri: http://token.url
        registration:
          support-management:
            client-id: the-client-id
            client-secret: the-client-secret
